#!/bin/bash
sudo apt install libmysqlclient-dev
sudo cpan -i DBI
sudo cpan -i DBD::mysql
sudo cpan -i Email::Valid
sudo cpan -i Email::Simple;
sudo cpan -i Email::Simple::Creator;
sudo cpan -i Email::Sender::Simple
exit 0
